### ISSUE TITLE
Invalid Format for Runner Row

### ISSUE THREAD

**Issue by Eli-code1** [flopp/parkrun-milestones#18]
Hi there! I've been trying to re-setup the milestone tool to tell me which milestones are coming up. When I last used it (~9 months ago), it seemed to work great, but now, I'm getting the following error when running the command on `eastville`:
```
-- Fetching data for Eastville parkrun...
-- Fetching the latest 10 result lists...
panic: while parsing results for eastville from www.parkrun.org.uk/eastville/278: runner row 0 - invalid format: <tr class="Results-table-row" data-name="David GUO" data-agegroup="SM25-29" data-club="" data-groups="" data-gender="Male" data-position="1" data-runs="179" data-vols="13" data-agegrade="72.68" data-achievement=""><td class="Results-table-td Results-table-td--position">1</td><td class="Results-table-td Results-table-td--name"><div class="compact"><a href="/eastville/parkrunner/2305995" target="_top">David GUO</a></div><div class="detailed">179 parkruns<span class="Results-tablet Results-tablet--inline"><span class="spacer"> | </span><span class="Results-table--M">                               Male                             </span>1<span class="Results-table--genderCount" data-gender="Male">                                                     </span></span><span class="spacer"> | </span><a href="https://www.parkrun.com/about/our-clubs/" class="milestone-r100 Results-table--clubIcon Results-table--100club" title="Member of the 100 Club">                         Member of the 100 Club                       </a></div><div class="Results-tablet"><div class="detailed">SM25-29<span class="spacer"> | </span>72.68%                           </div></div></td><td class="Results-table-td Results-table-td--gender Results-table-td--M"><div class="compact">                         Male                       </div><div class="detailed">1<span class="Results-table--genderCount" data-gender="Male">                                                 </span></div></td><td class="Results-table-td Results-table-td--ageGroup"><div class="compact">SM25-29</div><div class="detailed">72.68% age grade</div></td><td class="Results-table-td Results-table-td--club"> </td><td class="&#10;                        Results-table-td Results-table-td--time&#10;                      "><div class="compact">17:45</div><div class="detailed"><span class="Results-table--normal">PB</span> 16:57</div></td></tr>

goroutine 1 [running]:
main.main()
        /workspaces/parkrun-milestones/cmd/milestones/main.go:100 +0xf9c
```

Am I running something incorrectly? I'm doing the work inside a codespace with Go installed and the commands built. Thanks!

**Comment by robleady** [comment]
I'm seeing the same issue.
I'm guessing that the format of the results pages might have changed slightly.

**Comment by flopp** [comment]
Fixed in go-parkrunparser: https://github.com/flopp/go-parkrunparser/issues/4

**Comment by Eli-code1** [comment]
Ok awesome! @flopp will that get merged over into this repository? I have minimal experience with how Go works, so I don't know how deps and stuff are structured.

**Comment by flopp** [comment]
@Eli-code1 the dependencies have already been updated. So, when you update your installation, you should also get the fixed parser

**Comment by Eli-code1** [comment]
I'm now getting the following error:

```
-- Fetching data for Eastville parkrun...
panic: while parsing eventhistory of eastville from www.parkrun.org.uk/eastville/eventhistory: cannot find number of results

goroutine 1 [running]:
main.main()
        /workspaces/parkrun-milestones/cmd/milestones/main.go:100 +0xf9c
```

Is it working for you @flopp ?

**Comment by flopp** [comment]
@Eli-code1 hm, "Eastville" is working fine for me. 

I even added the current "eventhistory" page of eastville to the testset of go-parkrunparser: https://github.com/flopp/go-parkrunparser/commit/658cec73cb0435ed7af70ccdb8fae4c198aa0d77

Maybe something is wrong with the downloaded file.

Can you attach the downloaded file here, so that I can inspect it? 
* Mac: "$HOME/Library/Caches/parkrun-milestones/www.parkrun.org.uk/eastville/eventhistory"
* Linux: "$HOME/.cache/parkrun-milestones/www.parkrun.org.uk/eastville/eventhistory"

**Comment by Eli-code1** [comment]
Yeah, it looks like the file is blank. My suspicion is, since I'm running it on a codespace, that there could be something on the parkrun end that's preventing the call from going through. Oh well! Thanks for the help @flopp ! Perhaps I'll just install Go onto my Mac and figure it out (it's always fun to learn a new language 😄).

**Comment by flopp** [comment]
Ok, that makes sense.
