### ISSUE TITLE
Milestones evaluation broken

### ISSUE THREAD

**Issue by alexlomas** [flopp/parkrun-milestones#6]
./parkrun-milestones bushy
-- Fetching data for Bushy parkrun...
panic: bushy: missing run #1

goroutine 1 [running]:
main.main()
	/Users/x/Documents/parkrun-milestones/cmd/milestones/main.go:100 +0xb38

The regex for patternNumberOfRuns and patternRunRow from event.go looks correct at first glance but I'm assuming the website has subtly changed somewhere in the past couple of weeks, I just can't spot where.

**Comment by flopp** [comment]
Thanks for the report. I will have a look...

**Comment by flopp** [comment]
The date format in attributes of the 'eventhistory' table has changed.

Old: DD/MM/YYYY
New: YYYY-MM-DD

That is causing the parser to error out.

**Comment by flopp** [comment]
Fixed by 6eabe5a
